(0.8.0rc1) Only allow "YES"/"NO" in `add_label()` (#51)
* Convert PASS/FAIL to YES/NO

* Change to classmethod

* Remove logger

* Bump 0.8.0

* Only allow YES/NO labels through SDK; Add tests

* Add comments

* Remove duplicates

* Feedback

* Add type ignore

* Remove select all

* Enum

diff --git a/code-quality/lint b/code-quality/lint
--- a/code-quality/lint
+++ b/code-quality/lint
@@ -36,8 +36,8 @@ echo "Linting with mypy (type checking) ..."
 poetry run mypy $TARGET_PATHS || ((errors++))
 
 if [[ $errors -gt 0 ]]; then
-    echo "🚨 $errors linters found errors!"
-    exit $errors
+  echo "🚨 $errors linters found errors!"
+  exit $errors
 fi
 
 echo "✅ Success!"
